user-props:
  mark-down-path: C:\Users\wangn\Desktop\post
  db-file-path: C:\Users\wangn\Desktop\a.db
  hexo-cmd-path: G:\\Library_WEB\\hexo.cmd
  working-dir: G:\\ProjectData\\WebstormProjects\\itningblog\\